version: '3.8'

services:
  postgresDB:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotel_reservation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadminView:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgresDB
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge